version: '2.4'

services:

  yolov8:
    image: yolov8
    privileged: true
    build:
      context: .
      dockerfile: dockerfile_ros
    network_mode: "host"
    runtime: "nvidia"
    volumes:
      - /dev/bus/usb:/dev/bus/usb
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ../../yolov8_ros:/root/yolo
    environment:
      - ROS_MASTER_URI=http://127.0.0.1:11311
      - ROS_IP=127.0.0.1
      - DISPLAY
      - QT_X11_NO_MITSHM=1
    command: bash -c "source catkin_ws/devel/setup.bash; ROS_NAMESPACE=pose_estimator python ./yolo/detect_ros_seg.py --weights ./yolo/runs/segment/train10/weights/best.pt --conf-thres 0.9 --camera-topic '$$(rosparam get /pose_estimator/color_topic)'"
    stdin_open: true
    tty: true 